{{- if eq .Values.logs.enabled true -}}
  {{- if .Values.global.newrelic.enabled -}}
    {{- range $teamName, $teamInfo := .Values.global.newrelic.teams }}
      {{- if and (not $teamInfo.licenseKey.secretRef) $teamInfo.licenseKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nrotel.daemonsetName" $ }}-{{ $teamName }}
  namespace: {{ $.Release.Namespace }}
data:
  licenseKey: {{ $teamInfo.licenseKey.value | b64enc }}
---
      {{- end -}}
    {{- end -}}
  {{- else -}}
      {{- range $teamName, $teamInfo := .Values.daemonset.newrelic.teams }}
        {{- if and (not $teamInfo.licenseKey.secretRef) $teamInfo.licenseKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nrotel.daemonsetName" $ }}-{{ $teamName }}
  namespace: {{ $.Release.Namespace }}
data:
  licenseKey: {{ $teamInfo.licenseKey.value | b64enc }}
---
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
