{{- if eq .Values.traces.enabled true -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-dep
  namespace: {{ .Release.Namespace }}
data:
{{- range $teamName, $teamInfo := .Values.deployment.newrelic }}
  {{ $teamName }}: {{ $teamInfo.licenseKey | b64enc }}
{{- end -}}
{{- end -}}
