{{- if eq .Values.traces.enabled true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-dep
  namespace: {{ .Release.Namespace }}
  {{- if .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.statefulset.serviceAccount.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end -}}
