{{- if eq .Values.logs.enabled true -}}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Values.name }}-dep-rec
  namespace: {{ .Release.Namespace }}
spec:

  # Mode
  mode: "deployment"

  # Service Account
  serviceAccount: {{ .Values.name }}-dep

  # Ports to expose per service
  ports:
    - name: prometheus
      protocol: TCP
      port: {{ .Values.deployment.ports.prometheus.port }}
      targetPort: {{ .Values.deployment.ports.prometheus.targetPort }}

  # Image
  image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
  imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}

  # Resources
  resources:
    requests:
      cpu: {{ .Values.deployment.resources.requests.cpu }}
      memory: {{ .Values.deployment.resources.requests.memory }}
    limits:
      cpu: {{ .Values.deployment.resources.limits.cpu }}
      memory: {{ .Values.deployment.resources.limits.memory }}

  # Environment variables
  env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  {{- range $teamName, $teamInfo := .Values.daemonset.newrelic }}
  {{- if eq $teamName "opsteam" }}
    - name: {{ $teamName }}-endpoint
      value: {{ $teamInfo.endpoint }}
    {{- if $teamInfo.licenseKey.secretRef }}
    - name: {{ $teamName }}-licenseKey
      valueFrom:
        secretKeyRef:
          name: {{ $teamInfo.licenseKey.secretRef.name }}
          key: {{ $teamInfo.licenseKey.secretRef.key }}
    {{- else if $teamInfo.licenseKey.value }}
    - name: {{ $teamName }}-licenseKey
      valueFrom:
        secretKeyRef:
          name: {{ $.Values.name }}-dep-{{ $teamName }}
          key: licenseKey
    {{- end }}
  {{- end }}
  {{- end }}

  # Otel configuration
  config: |
    receivers:
      prometheus/self:
        config:
          scrape_configs:
            - job_name: 'otelcollector'
              scrape_interval: 10s
              static_configs:
              - targets:
                - 0.0.0.0:{{ .Values.deployment.ports.prometheus.port }}
      otlp:
        protocols:
          grpc:
          http:

    processors:
      cumulativetodelta:
      k8sattributes:
        extract:
          metadata:
          - k8s.node.name
          - k8s.namespace.name
          - k8s.pod.name
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      attributes:
        actions:
          - key: k8s.cluster.name
            value: {{ .Values.clusterName }}
            action: upsert
      attributes/self:
        actions:
          - key: otelcollector.type
            value: deployment-receiver
            action: upsert
          - key: k8s.node.name
            value: $MY_NODE_NAME
            action: upsert
          - key: k8s.namespace.name
            value: $MY_NAMESPACE_NAME
            action: upsert
          - key: k8s.pod.name
            value: $MY_POD_NAME
            action: upsert
      memory_limiter:
         check_interval: 1s
         limit_percentage: 80
         spike_limit_percentage: 25
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800

    exporters:
      loadbalancing:
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          dns:
            hostname: "{{ .Values.name }}-dep-exp-collector-headless.{{ .Release.Namespace }}.svc.cluster.local"
      otlp/opsteam:
        endpoint: ${opsteam-endpoint}
        tls:
          insecure: false
        headers:
          api-key: ${opsteam-licenseKey}
      logging:
        verbosity: detailed

    extensions:
      memory_ballast:
        size_in_percentage: 20

    service:
      extensions:
        - memory_ballast
      pipelines:
        metrics/self:
          receivers:
            - prometheus/self
          processors:
            - cumulativetodelta
            - k8sattributes
            - attributes
            - attributes/self
            - memory_limiter
            - batch
          exporters:
            - otlp/opsteam
            # - logging
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - k8sattributes
            - attributes
            - batch
          exporters:
            - loadbalancing
            # - logging
      telemetry:
        # logs:
        #   level: DEBUG
        metrics:
          address: 0.0.0.0:{{ .Values.deployment.ports.prometheus.targetPort }}
{{- end -}}
