{{- if eq .Values.metrics.enabled true -}}
{{- range $teamName, $teamInfo := .Values.statefulset.newrelic }}
{{- if and (not $teamInfo.licenseKey.secretRef) $teamInfo.licenseKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.name }}-sts-{{ $teamName }}
  namespace: {{ $.Release.Namespace }}
data:
  licenseKey: {{ $teamInfo.licenseKey.value | b64enc }}
---
{{- end -}}
{{- end -}}
{{- end -}}
