apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-sts
  {{- if .Values.statefulset.clusterRoleBinding.annotations }}
  annotations:
    {{- range $key, $value := .Values.statefulset.clusterRoleBinding.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}-sts
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-sts
  namespace: {{ .Release.Namespace }}
