apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  {{- if .Values.clusterRole.annotations }}
  annotations:
    {{- range $key, $value := .Values.clusterRole.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
rules:
  {{- if .Values.clusterRole.rules -}}
  {{ toYaml .Values.clusterRole.rules | nindent 2 -}}
  {{- end }}
