### Variables

# Name
name: "otelcollectordeploy"

# Image
image:
  # Repository
  repository: otel/opentelemetry-collector-contrib
  # Image pull policy
  pullPolicy: IfNotPresent
  # Image tag
  tag: "0.74.0"

# Service account
serviceAccount:
  # Annotations to add to the service account
  annotations: {}

clusterRole:
  # Annotations to add to the clusterRole
  # Can be used in combination with presets that create a cluster role.
  annotations: {}
  # A set of rules as documented here : https://kubernetes.io/docs/reference/access-authn-authz/rbac/
  # Can be used in combination with presets that create a cluster role to add additional rules.
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - watch
        - list

clusterRoleBinding:
  # Annotations to add to the clusterRoleBinding
  # Can be used in combination with presets that create a cluster role binding.
  annotations: {}

# Array of key value pairs defining the ports for the
# collector to expose
ports:
  # Prometheus
  prometheus:
    name: prometheus
    protocol: TCP
    port: 8888
    targetPort: 8888

# Resource limits & requests. Update according to your own use case as these values might be too low for a typical deployment.
resources:
  requests:
    cpu: 32m
    memory: 128Mi
  limits:
    cpu: 256m
    memory: 512Mi

# New Relic account configuration
newrelic:
  # OPS team which is responsible for the cluster and common apps
  # running on it.
  opsteam:
    endpoint: "otlp.nr-data.net:4317"
    licenseKey: ""
    namespaces: []

  # # If you want to send the namespaced telemetry data from the
  # # cluster to the accounts of the individual dev teams
  # # comment in below.
  # # Dev team 1 which is responsible for its own apps running
  # # in a specific namespace.
  # devteam1:
  #   endpoint: "otlp.nr-data.net:4317"
  #   licenseKey: ""
  #   namespaces:
  #     - devteam1
  # # Dev team 2 which is responsible for its own apps running
  # # in a specific namespace.
  # devteam2:
  #   endpoint: "otlp.nr-data.net:4317"
  #   licenseKey: ""
  #   namespaces:
  #     - devteam2
